version: "3"

services:
  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb:/data/db
  node:
    build: .
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/bhtu
    ports:
      - 3000:3000

volumes:
  mongodb:
